#define CODE_BALANCE_REQUEST  	0x01
#define CODE_TRANSFER_REQUEST 	0x02
#define CODE_LIST_REQUEST    	0x03

#define CODE_BALANCE_RESPONSE	0x04
#define CODE_TRANSFER_RESPONSE 	0x05
#define CODE_LIST_RESPONSE_1 	0x06
#define CODE_LIST_RESPONSE_2 	0x07
